### PR TITLE
squangle soft line location error

### PR DESCRIPTION
**Pull request by huzhiguang**
Can't find squangle path error caused by mysql include file

### CODE REVIEW

**Comment by jwatzman** [comment]
@fredemmott you added squangle right? Does this look right to you? Curious why we didn't hit this before -- do we not use this symlink? Can we kill it?

**Comment by fredemmott** [comment]
This looks wrong - 'src -> src/squangle ' would be a recursive symbolic link

**Comment by fredemmott** [comment]
Closing this. Please respond to previous comment if you still feel a change is needed.

**Comment by huzhiguang** [comment]
You can try compile hhvm, hhvm will throw compile exception when compile hhvm.
Exception message:

	hhvm-HHVM-3.6/third-party/squangle/src/mysql_client/Row.cpp:10:39: fatal error: squangle/mysql_client/Row.h: No such file or directory   
 	#include "squangle/mysql_client/Row.h"

This error message is don't find squangle directory,because squangle path is error.
You can see squangle CMakeList.txt,include dirctorires is src,tut  squangle directory don't in src directory,so throw error don't find squangle dirctory when compile hhvm.

CMakeList: 

	include_directories("${CMAKE_CURRENT_SOURCE_DIR}/src" ${RE2_INCLUDE_DIR} ${MYSQL_INCLUDE_DIR})

And then you can see folly ,thrift and so on configure path,they configure path is src/xxxx.

**Comment by fredemmott** [comment]
We do compile HHVM, and it works for us. Please respond to the comment about this creating a recursive symbolic link.

**Comment by huzhiguang** [comment]
Because this path don't find squangle directory,so I create this symbolic link.
You can see CMakeList.txt include_directories is src,and then src link squangle ,but Row.cpp include dirctory is "squangle/mysql_client/Row.h" rather than "mysql_client/Row.h",so this include path "squangle/xxxx" will go to hhvm-third-party/squangle/src->(real path)hhvm-third-party/squangle/squangle to find,but hhvm-third-party/squangle/src directory does not exist squangle  directory,so Row.cpp throw error don't find squangle dirctory when compile hhvm .

I don't know if I said you can understand.Thanks.

**Comment by fredemmott** [comment]
- I can't reproduce the issue
- I don't see how this PR could fix your symptoms. It creates a recursive symbolic link - how does an unresolvable link fix things?

**Comment by sgolemon** [comment]
@huzhiguang Could you try compiling with https://github.com/hhvm/hhvm-third-party/commit/e658103ce2634cc38cb214d2c98aaf13f0f21f08 instead of your diff?  I think it'll solve your issue correctly (without any filesystem loops)

**Pull request closed without merging**
