### PR TITLE
Update opam to opam 2.0.2

### PR DESCRIPTION
**Pull request by vsiles**
opam 1.2 is deprecated, updating to opam 2.0.2

Now for its dependencies, opam supports local archives of tgz file, or getting
them from the internet + check md5 sum. I choose the latter. The list of
versions of md5 files can be found in opam/src_ext/Makefile.sources

Note that hhvm will require a fix to opam_setup.sh

Test plan:
build commands remains the same, this must not affect the current
workflow

### CODE REVIEW

**Comment by vsiles** [comment]
Depends on https://github.com/facebook/hhvm/pull/8447

**Comment by fredemmott** [comment]
LGTM, but cc @vassilmladenov ; if this ends up being rebased etc, the hhvm PR will need updating to reference the correct commit hash.

**Comment by fredemmott** [comment]
@vsiles: commit ID has changed, the hhvm commit will need updating

**Comment by fredemmott** [comment]
the submodule should be referencing 95de68b5c7848d75a906e3f50764885f1db81b1f

**Pull request merged**
