### PR TITLE
remove old curl patches

### PR DESCRIPTION
**Pull request by jrobeson**
i removed the reference to the libcurl patch as well. I don't see
why anybody would build with an old curl on purpose.

### CODE REVIEW

**Comment by jrobeson** [comment]
any reason not to merge this?

**Comment by paulbiss** [comment]
Seems reasonable, @fredemmott @jwatzman any objections?

**Comment by fredemmott** [comment]
I'm happy.

**Comment by jwatzman** [comment]
Oops, I thought I *had* merged this. Thanks!

**Pull request merged**
