### PR TITLE
update webscalesqlclient submodule to facebook/mysql-5.6

### PR DESCRIPTION
**Pull request by drilibo**
Summary:
Manually changed .gitmodules then:
git submodule update --init --recursive
git pull origin webscalesql-5.6.24.97
git add webscalesqlclient
```
   hhvm-third-party/webscalesqlclient/src $ git log

   commit 896ecfc2e5d141dbab451a104c24da644ac5ea6b
   Author: Dan Reif <dreif@fb.com>
   Date:   Thu Oct 8 21:35:38 2015 -0700
```

### CODE REVIEW

**Comment by JoelMarcey** [comment]
cc: @jwatzman (current on-call)

According to an email thread, @fredemmott seems onboard with this change. We would have accept this patch and then update the HHVM third-party hash.

I think that this is fine.

**Comment by jwatzman** [comment]
Yeah, I want to make sure to test this on Linux and OS X, and haven't gotten around to that yet. Probably later today.

**Comment by jwatzman** [comment]
The way this is done fails to update existing trees. From inside the `third-party` directory:

```sh
$ git pull https://github.com/drilibo/hhvm-third-party.git updatewebscale
From https://github.com/drilibo/hhvm-third-party
 * branch            updatewebscale -> FETCH_HEAD
Updating 2500669..8ea182b
Fast-forward
 .gitmodules                       | 2 +-
 CMakeLists.txt                    | 3 +--
 libzip/zipint.h                   | 2 +-
 thrift/CMakeLists.txt             | 3 +++
 webscalesqlclient/CMakeLists.txt  | 5 +++--
 webscalesqlclient/webscalesql-5.6 | 2 +-
 6 files changed, 10 insertions(+), 7 deletions(-)
$ git submodule update --init --recursive
fatal: reference is not a tree: 896ecfc2e5d141dbab451a104c24da644ac5ea6b
Unable to checkout '896ecfc2e5d141dbab451a104c24da644ac5ea6b' in submodule path 'webscalesqlclient/webscalesql-5.6'
```

**Comment by drilibo** [comment]
It does seem like you need to clean the repo to make this work without
changing the submodule path. I tried changing just the name of the
submodule in a already initialized git repo and it failed.

**Comment by jwatzman** [comment]
Yeah, and we can't insist that everyone with every checkout should re-clone it, particularly since the error message is pretty inscrutable. Is there something else we can do here, ideally without changing the paths?

**Comment by drilibo** [comment]
abandoning this one
https://github.com/hhvm/hhvm-third-party/pull/91 tried another approach

**Pull request closed without merging**
