### PR TITLE
Add the Intel XED library

### PR DESCRIPTION
**Pull request by catalin-manciu**
This adds the Intel XED library, required by https://github.com/facebook/hhvm/pull/8164

### CODE REVIEW

**Comment by catalin-manciu** [comment]
@fredemmott Currently the Travis build fails due to **xed** not having an entry in the util/make-notices.hh script file. Changing that script (which has a different license than HHVM) would require me to go through an internal process which would take a few weeks.
In the interest of expediting this, would you kindly add an entry to the array returned by `ThirdPartyBinaryNotices::getKnownProjects()` containing the library's name - `'Intel XED Library'` - and the path to its copyright notice - `'xed/xed/LICENSE'`?

**Comment by fredemmott** [comment]
Sorry - as I understand it, that request is basically equivalent to sending a diff, so we'll need it officially contributed by Intel under the CLA.

I can't guarantee that this will happen, but FYI I've also requested review to relicense that script under MIT rather than the BSD+PATENTS license.

**Comment by fredemmott** [comment]
@catalin-manciu : I'll have this under the MIT license in the next day or two.

**Comment by fredemmott** [comment]
@catalin-manciu : we've made the change to the notices script as a one-off exception. In general, we will continue to require pull requests for almost all changes.

**Comment by catalin-manciu** [comment]
@fredemmott Thank you for your help !

**Pull request merged**
