### PR TITLE
Update to proxygen(19:0) and folly(34:0)

### PR DESCRIPTION
**Pull request by ckwalsh**

### CODE REVIEW

**Comment by jwatzman** [comment]
- I assume you did a test build with this?
- What's in the new proxygen you want to use?

(In general, lgtm, just double-checking.)

**Comment by ckwalsh** [comment]
Hold off on merging this for a bit, I'll put up some cmake changes too. I'm
wanting to build proxygen/lib/http so we can import the proxygen hhvm
server into github

**Comment by jwatzman** [comment]
Cool, LMK when this is good to go.

**Comment by ckwalsh** [comment]
Alright, this is ready now

**Pull request merged**
