### PR TITLE
Add headers to the libraries

### PR DESCRIPTION
**Pull request by Orvid**
DO NOT MERGE! - This is currently broken due to some changes I made while separating this out of my main build.

This also switches to `HHVM_REMOVE_MATCHES_FROM_LISTS`, and adds `auto_source_group` calls as well.

This was done as a single commit because they would end up conflicting with each other or else need to be updated after one is merged.

### CODE REVIEW

**Comment by jwatzman** [comment]
Can you remind me why the headers are important to include here?

@sgolemon @JoelMarcey does this look good to you?

**Comment by Orvid** [comment]
The headers are important because otherwise the files don't show up as part of the project in Visual Studio, which makes it a pain to get to some of the headers to edit them.

**Comment by JoelMarcey** [comment]
I am going to leave the final response to @sgolemon since she knows cmake stuff better than me, but I am wondering...

I didn't look too closely, but do we generally force a dependency of `hhvm-third-party` on `hhvm`? `HHVM_REMOVE_MATCHES_FROM_LISTS` is defined in our hhvm repo, not in the third party repo. So with this call, this repo is now dependent on hhvm -- when I thought it should generally be the other way around where hhvm is dependent on this repo.

**Comment by Orvid** [comment]
`auto_sources` and `auto_source_group` are both defined in the main HHVM side as well.

**Comment by Orvid** [comment]
Also, this has a few issues that I still need to correct, due to most of the libs not including the headers in my normal build. As this includes the headers in the source_group calls, a few more paths need to be excluded.

**Comment by fredemmott** [comment]
What should be happening here?

**Comment by Orvid** [comment]
I need to go through and check this, it's not one that I'm currently using, but it should be fine once rebased.

**Pull request closed without merging**
