### PR TITLE
Fix bug with "last day of <monthname>" in strtotime().

### PR DESCRIPTION
**Pull request by jazzdan**
Backport https://github.com/php/php-src/commit/ffbd380e4483a5b36733cfd99fab779008082d11
to HHVM's timelib.

This fixes a bug with "last day of <monthname>" in strtotime in HHVM demonstrated here http://3v4l.org/gJ5f7.

It should resolve facebook/hhvm#4977.

Thanks to @bcharas for helping me chase this down.

### CODE REVIEW

**Comment by jwatzman** [comment]
This is a reimport of PHP5's timelib, right? Anything interesting other than just copying over their code?

**Comment by jazzdan** [comment]
Hey @jwatzman,

It's a reimport, but only up to a point. @fredemmott mentioned that last time he did a full import a bunch of tests broke so I cherry-picked only the commit I needed from PHP5's timelib.

**Comment by jwatzman** [comment]
@fredemmott you mentioned something this morning about a full refresh of timelib to fix a bunch of issues, including some code changes. Does that subsume this, or should we merge this now?

**Comment by fredemmott** [comment]
We should merge this for now; internal builds use a different version.

**Comment by jwatzman** [comment]
Done, thanks @jazzdan!

**Pull request merged**
