### PR TITLE
Update PCRE from version 8.32 to 8.36.

### PR DESCRIPTION
**Pull request by kaiokaram**
Execution of regular expression functions does not work when HHVM is executed on PowerPC. In order to solve this problem, library PCRE was updated from version 8.32 to version 8.36.

### CODE REVIEW

**Comment by jwatzman** [comment]
Looks reasonable to me, and passes `quick` and `slow/ext_preg` tests with this applied. @sgolemon et al, any other thoughts? Otherwise lgtm to merge.

**Comment by apinski-cavium** [comment]
This needed also for ARM64.  I just did the same too.

**Comment by jwatzman** [comment]
Woah, sorry for forgetting about this. Running another testing round now.

**Comment by jwatzman** [comment]
Thanks!

**Pull request merged**
